// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://elphtzirpvwgaguhofta.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVscGh0emlycHZ3Z2FndWhvZnRhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5NDg1NjksImV4cCI6MjA3MTUyNDU2OX0.vZDxZzhPWPVW1upmKywn_eC0UUt8UJtG84i79PXq95s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});